### ISSUE TITLE
How should i set validate-fix-genprog.sh mannualy

### ISSUE THREAD

**Issue by yodahaji** [codeflaws/codeflaws#5]
i find in the top lines of this file should be set by the user self. compare to the run-version-genprog.sh,
i find the second line of this file lacks two " symble. 

after set the first line as it is in  run-version-genprog.sh,i find there should be 4 argument input by the user. 
although the names are give,i think the meaning and the usage isn't very clear yet.

the first argument ,version, i have guessed genprog/71-A-bug-18359456-18359477/tempworkdir-71-A-bug-18359456-18359477/temp-71-A-bug-18359456-18359477.out/71-A-18359456.c/temp-71-A-bug-18359456-18359477 ,but every one seems wrong

the second argument , filen , i guessed this means the number of files, or the number of lines in the copy of codeflaws-defect-detail-info.txt . because i only tested one line,i put 1.

the third argument,repairdir, i make this same with the path to the genprog in the  run-version-genprog.sh.

the fourth argument,timespent, i think this is the time spended in this test,but i don't get the stat , so i input 10 as a try.

after thar,the command line hints grep -1 : no such file or directory.

maybe the meaning of  the first or the third argument are misunderstood by me. Or because i dont run run-version-genprog.sh? 

sorry for again and again interrupt.

**Comment by stan6** [comment]
I think that you may misunderstood the meaning of running validate-fix.sh. Note hat validate-fix.sh only can be run if fix is generated(after you run run-version-<tool>.sh and it checks if the automatically generated repair is correct with respect to held out tests. For example, you will find a tempworkdir-<version>/repair* directory for genprog if a fix is generated. If no fix is generated,then validate-fix-genprog.sh cannot be run since there is no fix to validate. Only changing the $rundir variable is enough for running it with run-version-<tool> file.

**Comment by yodahaji** [comment]
Thanks for quick reply.
