### ISSUE TITLE
# of defects in Codeflaws.

### ISSUE THREAD

**Issue by fermadeiral** [codeflaws/codeflaws#6]
In the readme of Codeflaws repo, it has been said that the Codeflaws contains 4085 defects (twice). However, I found only 3902 defects in http://www.comp.nus.edu.sg/~release/codeflaws/codeflaws.tar.gz file.

Has Codeflaws evolved?

**Comment by stan6** [comment]
Hi, thank you for pointing out the inconsistencies. Yes, the number of defects in the README.md is outdated. It should be 3902 defects as stated in the website (https://codeflaws.github.io/) and descriptions of this repository. I have updated the README.md to reflect the correct number.

> Has Codeflaws evolved

The number of defects is updated because some defects are removed as they are irreproducible.
