### ISSUE TITLE
From DefectTable, Github Link for each bug is not accessible  

### ISSUE THREAD

**Issue by SamraMehboob** [codeflaws/codeflaws#9]
Hi, 
I was trying to access type of bugs mentioned in defect table. Can you please update link in defect table or help me with this.
**https://codeflaws.github.io/defect-table.html**

Looking forward to your response. 
Thank you.

**Comment by stan6** [comment]
Dear @SamraMehboob,

Thank you for your interest in Codeflaws. The broken link is due to the removal of the benchmark folder by @mechtaev. Sergey will fix the problem.

Meanwhile, for temporary workaround, there are two solutions:

1. You can download the benchmark at [tar-link](http://www.comp.nus.edu.sg/~release/codeflaws/codeflaws.tar.gz) and look the defect type within the folder
2. Revert to the [previous version](https://github.com/codeflaws/codeflaws/tree/7b4622922ae31e9b55a00cee7046b65fa014c45b/benchmark) where the benchmark folder was not removed

**Comment by SamraMehboob** [comment]
Thank you for response. I'll try by reverting to previous version.
